// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const url = import.meta.env.VITE_SUPABASE_URL || (import.meta.env.VITE_SUPABASE_PROJECT_ID ? `https://${import.meta.env.VITE_SUPABASE_PROJECT_ID}.supabase.co` : "");
const key = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase: SupabaseClient<Database> | null = (url && key)
  ? createClient<Database>(url, key, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    })
  : null;

if (!supabase) {
  const url = import.meta.env.VITE_SUPABASE_URL;
  const key = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
  
  if (!url || !key) {
    console.error("❌ Supabase não está configurado!");
    console.error("Variáveis de ambiente necessárias:");
    console.error("  - VITE_SUPABASE_URL:", url ? "✅ Configurada" : "❌ Não configurada");
    console.error("  - VITE_SUPABASE_PUBLISHABLE_KEY:", key ? "✅ Configurada" : "❌ Não configurada");
    console.error("");
    console.error("Para corrigir:");
    console.error("  Local: Crie um arquivo .env.local com as variáveis");
    console.error("  Vercel: Configure as variáveis em Settings > Environment Variables");
    console.error("  GitHub: As variáveis devem ser configuradas no Vercel, não no código");
  }
}